// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV5w6eFsI63JdvDq9cVg6-HTtJI9oEfoM',
    appId: '1:750807066163:web:f47e09f9b41d1e74c62546',
    messagingSenderId: '750807066163',
    projectId: 'flutter-messenger-d91fc',
    authDomain: 'flutter-messenger-d91fc.firebaseapp.com',
    storageBucket: 'flutter-messenger-d91fc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsg0xt2n1quYkf8xJ1zSy20mNmQqWb3CY',
    appId: '1:750807066163:android:e5161fb89ea66966c62546',
    messagingSenderId: '750807066163',
    projectId: 'flutter-messenger-d91fc',
    storageBucket: 'flutter-messenger-d91fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsdGAm4bprtz5cs-aEDli8kIcpoq-8_Gg',
    appId: '1:750807066163:ios:b8f606786b71a769c62546',
    messagingSenderId: '750807066163',
    projectId: 'flutter-messenger-d91fc',
    storageBucket: 'flutter-messenger-d91fc.appspot.com',
    iosBundleId: 'com.example.messager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsdGAm4bprtz5cs-aEDli8kIcpoq-8_Gg',
    appId: '1:750807066163:ios:ef50b9aaf2eb8f2ac62546',
    messagingSenderId: '750807066163',
    projectId: 'flutter-messenger-d91fc',
    storageBucket: 'flutter-messenger-d91fc.appspot.com',
    iosBundleId: 'com.example.messager.RunnerTests',
  );
}
